name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Sync with Upstream
        uses: repo-sync/github-sync@v3
        with:
          source_repo: umami-software/umami
          source_branch: master # Replace with the upstream branch name if different
          target_branch: master # Replace with your fork's branch name
          github_token: ${{ secrets.GITHUB_TOKEN }}
